In [3]:
%load_ext autoreload
%autoreload 2
import os
import sys
import pandas as pd

os.chdir(os.path.abspath('..'))


In [4]:
from dinov2.data.datasets.mmearth import MMEarthWrapper, MMEarth
base_path = '/data/panopticon/datasets/mmearth/data_1M_v001'

mme = MMEarthWrapper(base_path, modalities=MMEarth.MODALITY_MINIMAL_SET1, split='train')


data_1M_v001 /data/panopticon/datasets/mmearth/data_1M_v001/data_1M_v001.h5
Removed 589 rows that did not have sentinel1 data


In [5]:
len(mme)

1239937

In [6]:
sample = mme[-1]

sample['imgs'][0][0].shape,sample['chn_ids'][0], sample['imgs'][1][0].shape, sample['chn_ids'][1]

(torch.Size([12, 128, 128]),
 tensor([ 442,  492,  559,  664,  704,  740,  782,  832,  864,  945, 1613, 2202],
        dtype=torch.int32),
 torch.Size([4, 128, 128]),
 tensor([ -5,  -6,  -9, -10], dtype=torch.int32))

In [8]:
import numpy as np
np.isnan(sample['imgs'][0][0]).all(axis=(1, 2))

/data/tmp/ipykernel_2595401/4109547142.py:2: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  np.isnan(sample['imgs'][0][0]).all(axis=(1, 2))


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8)

In [13]:
mme.meta_full

id     s2_date s2_type         crs        lat         lon  \
0         966869  2018-07-23     l1c  EPSG:32618  10.725052  -74.436832   
1         717545  2017-11-11     l1c  EPSG:32648  30.042947  102.174004   
2         577901  2020-09-24     l1c  EPSG:32657  53.633647  158.703385   
3         538060  2017-07-28     l1c  EPSG:32647  65.269372  100.644807   
4         664133  2018-09-20     l2a  EPSG:32634  50.003281   20.537190   
...          ...         ...     ...         ...        ...         ...   
1239932  1279127  2020-08-12     l1c  EPSG:32736  -6.243885   32.153590   
1239933   626248  2020-05-09     l1c  EPSG:32608  63.724576 -134.834008   
1239934  1310906  2018-08-12     l1c  EPSG:32724 -12.083331  -41.660711   
1239935   425607  2019-02-06     l2a  EPSG:32637  22.885851   41.028868   
1239936   884751  2019-09-11     l2a  EPSG:32644  31.501607   82.378551   

         biome  eco_region  no_data  \
0            9         673    False   
1            6         532    False   
2            5         480    False   
3            5         475    False   
4            6         505    False   
...        ...         ...      ...   
1239932     11         768    False   
1239933      5         493    False   
1239934     12         779    False   
1239935      3         421    False   
1239936      8         634    False   

                                                     bands  \
0        {'aster': ['b1', 'slope'], 'canopy_height_eth'...   
1        {'aster': ['b1', 'slope'], 'canopy_height_eth'...   
2        {'aster': ['b1', 'slope'], 'canopy_height_eth'...   
3        {'aster': ['b1', 'slope'], 'canopy_height_eth'...   
4        {'aster': ['b1', 'slope'], 'canopy_height_eth'...   
...                                                    ...   
1239932  {'aster': ['b1', 'slope'], 'canopy_height_eth'...   
1239933  {'aster': ['b1', 'slope'], 'canopy_height_eth'...   
1239934  {'aster': ['b1', 'slope'], 'canopy_height_eth'...   
1239935  {'aster': ['b1', 'slope'], 'canopy_height_eth'...   
1239936  {'aster': ['b1', 'slope'], 'canopy_height_eth'...   

                                                      era5  hf5_idx  split  \
0        {'month1': [300.7351797527737, 296.75398254394...        0  train   
1        {'month1': [279.72476965381253, 270.1488952636...        1  train   
2        {'month1': [282.62446579881896, 274.5160522460...        2  train   
3        {'month1': [286.904347691458, 271.604249847515...        3  train   
4        {'month1': [293.93280952207505, 281.7649688720...        4  train   
...                                                    ...      ...    ...   
1239932  {'month1': [294.79952247953656, 286.3188744712...  1240521  train   
1239933  {'month1': [268.12983883751764, 251.8291015625...  1240522  train   
1239934  {'month1': [292.1041757111908, 285.00070190429...  1240523  train   
1239935  {'month1': [293.0026272394324, 279.38739013671...  1240524  train   
1239936  {'month1': [279.28749174712806, 269.9517669677...  1240525  train   

                                                    sensor  
0        [sentinel2, sentinel1_asc, sentinel1_desc, ast...  
1        [sentinel2, sentinel1_asc, sentinel1_desc, ast...  
2        [sentinel2, sentinel1_asc, sentinel1_desc, ast...  
3        [sentinel2, sentinel1_desc, aster, era5, dynam...  
4        [sentinel2, sentinel1_asc, sentinel1_desc, ast...  
...                                                    ...  
1239932  [sentinel2, sentinel1_asc, sentinel1_desc, ast...  
1239933  [sentinel2, sentinel1_asc, aster, era5, dynami...  
1239934  [sentinel2, sentinel1_desc, aster, era5, dynam...  
1239935  [sentinel2, sentinel1_asc, aster, era5, dynami...  
1239936  [sentinel2, sentinel1_asc, sentinel1_desc, ast...  

[1239937 rows x 14 columns]

In [10]:
import numpy as np
sample = mme[168269]
sample['imgs'][0][0].shape,sample['imgs'][1][0].shape, sample['chn_ids']

(torch.Size([13, 128, 128]),
 torch.Size([2, 128, 128]),
 [tensor([ 442,  492,  559,  664,  704,  740,  782,  832,  864,  945, 1373, 1613,
          2202], dtype=torch.int32),
  tensor([ -7, -11], dtype=torch.int32)])

In [13]:
mme.meta_full.iloc[-1]['bands']

{'aster': array(['b1', 'slope'], dtype=object),
 'canopy_height_eth': array(['height', 'std'], dtype=object),
 'dynamic_world': array(['label'], dtype=object),
 'era5': array(['201908_temperature_2m', '201908_temperature_2m_min',
        '201908_temperature_2m_max', '201908_total_precipitation_sum',
        '201909_temperature_2m', '201909_temperature_2m_min',
        '201909_temperature_2m_max', '201909_total_precipitation_sum',
        '0_temperature_2m_mean', '1_temperature_2m_min_min',
        '2_temperature_2m_max_max', '3_total_precipitation_sum_sum'],
       dtype=object),
 'esa_worldcover': array(['Map'], dtype=object),
 'sentinel1_asc': array(['VV', 'VH'], dtype=object),
 'sentinel1_desc': array(['VV', 'VH'], dtype=object),
 'sentinel2': array(['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8A', 'B8', 'B9', 'B11',
        'B12', 'MSK_CLDPRB', 'SCL', 'QA60'], dtype=object)}

In [8]:
sample['imgs'][0][0].shape, sample['imgs'][1][0].shape, sample['chn_ids'][1]

(torch.Size([13, 128, 128]),
 torch.Size([2, 128, 128]),
 tensor([ -7, -11], dtype=torch.int32))

In [13]:
import random

target = 1000

for n in range(target):
    i = random.randint(0, len(mme))
    # print(f'Indexing {i}')
    sample = mme[i]

    if np.isnan(sample['imgs'][0][0]).all(axis=(1, 2)).sum() > 0:
        print (f'Indexing {i} - S2 channels:{sample["chn_ids"][0]}')
    
    if np.isnan(sample['imgs'][1][0]).all(axis=(1, 2)).sum() > 0:
        print (f'Indexing {i} - S1 channels:{sample["chn_ids"][1]}')


/data/tmp/ipykernel_2595401/587998401.py:10: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  if np.isnan(sample['imgs'][0][0]).all(axis=(1, 2)).sum() > 0:
/data/tmp/ipykernel_2595401/587998401.py:13: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  if np.isnan(sample['imgs'][1][0]).all(axis=(1, 2)).sum() > 0:
